apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 4000       # The port exposed by the service
      targetPort: 4000 # The port on the container
  type: ClusterIP       # Internal communication within the cluster
