apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 80         # Port exposed for external access (or within the cluster)
      targetPort: 8888 # Container's Jupyter port
  type: LoadBalancer  # To expose it externally if needed, use NodePort if LoadBalancer is not available
