apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: ecastill05/rest-api:latest
        ports:
        - containerPort: 3001
        env:
        - name: GRAPHQL_ENDPOINT
          value: "http://graphql:4000" # Internal DNS resolution in Kubernetes
